#!/bin/sh
#
# Controls mstpd.
#

case $1 in
  start)
    printf "Starting mstpd: "
    start-stop-daemon -S -q -p /var/run/mstpd.pid --exec /sbin/mstpd
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "Stopping mstpd: "
    start-stop-daemon -K -q -p /var/run/mstpd.pid 
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
