#!/bin/sh
#
# Mount debugfs interface
#

case $1 in
  start)
    echo "Mounting debugfs..."
    mount -t debugfs none /sys/kernel/debug
    test -e /etc/dyndbg.txt && cat /etc/dyndbg.txt > \
      /sys/kernel/debug/dynamic_debug/control
    ;;
  stop)
    echo "Unmounting debugfs..."
    umount /sys/kernel/debug
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
